//data reducer types
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER'
export const SET_ALL_USER_LOANS = 'SET_ALL_USER_LOANS'
export const GET_MAX_AGREEMENTID = 'GET_MAX_AGREEMENTID'
export const GET_MAX_CUSTOMERID = 'GET_MAX_CUSTOMERID'

//user reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_AUTHENTICATED_USER_INFO = 'SET_AUTHENTICATED_USER_INFO'